http:
  port:         8080
  maxHeaderBytes:  1  # MegaBytes
  readTimeout:    30  # Seconds
  writeTimeout:   30  # Seconds
  shutdownTimeout: 5  # Seconds

database:
  requestTimeout:     5 # Seconds
  connectionTimeout: 10 # Seconds
  shutdownTimeout:    5 # Seconds